version: '3.8'

services:
  flask_app:
    build:
      context: ./Interface  # The directory containing Dockerfile and app files
      
    container_name: flask_app_container
    ports:
      - "5001:5001"
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    networks:
      - wm-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wm-network

volumes:
  mongo-data:

networks:
  wm-network:
    driver: bridge
