# version: '3.1'

services:

 redis:
    image: arm64v8/redis:latest

    container_name: my-redis
#    volumes:
#      - ./data/redis:/data
    networks:
      - redis_net
    ports:
      - 6378:6379

#  redis-commander:
#     container_name: redis-commander
#     image: arm64v8/redis:latest
#     environment:
#     - REDIS_HOSTS=local:my-redis:6379
#     ports:
#     - "8081:8081"
#     networks:
#       - redis_net

networks:
  redis_net:
    external:  false

version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
